export const mockObj = [
  {
    idMeal: "52802",
    strMeal: "Fish pie",
    strMealAlternate: null,
    strCategory: "Seafood",
    strArea: "British",
    strInstructions:
      "01.Put the potatoes in a large pan of cold salted water and bring to the boil. Lower the heat, cover, then simmer gently for 15 minutes until tender. Drain, then return to the pan over a low heat for 30 seconds to drive off any excess water. Mash with 1 tbsp olive oil, then season.\r\n02.Meanwhile put the milk in a large sauté pan, add the fish and bring to the boil. Remove from the heat, cover and stand for 3 minutes. Remove the fish (reserving the milk) and pat dry with kitchen paper, then gently flake into an ovenproof dish, discarding the skin and any bones.\r\n03.Heat the remaining oil in a pan, stir in the flour and cook for 30 seconds. Gradually stir in 200-250ml of the reserved milk (discard the rest). Grate in nutmeg, season, then bubble until thick. Stir in the cream.\r\n04.Preheat the oven to 190°C/fan170°C/gas 5. Grate the artichokes and add to the dish with the leek, prawns and herbs. Stir the lemon zest and juice into the sauce, then pour over. Mix gently with a wooden spoon.\r\n05.Spoon the mash onto the fish mixture, then use a fork to make peaks, which will crisp and brown as it cooks. Sprinkle over the cheese, then bake for 35-40 minutes until golden and bubbling. Serve with wilted greens.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
    strTags: "Fish,Pie,Breakfast,Baking",
    strYoutube: "https://www.youtube.com/watch?v=2sX4fCgg-UI",
    strIngredient1: "Floury Potatoes",
    strIngredient2: "Olive Oil",
    strIngredient3: "Semi-skimmed Milk",
    strIngredient4: "White Fish Fillets",
    strIngredient5: "Plain flour",
    strIngredient6: "Nutmeg",
    strIngredient7: "Double Cream",
    strIngredient8: "Jerusalem Artichokes",
    strIngredient9: "Leek",
    strIngredient10: "Prawns",
    strIngredient11: "Parsley",
    strIngredient12: "Dill",
    strIngredient13: "Lemon",
    strIngredient14: "Gruyère",
    strIngredient15: "Lemon",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "900g",
    strMeasure2: "2 tbsp",
    strMeasure3: "600ml",
    strMeasure4: "800g",
    strMeasure5: "1 tbsp",
    strMeasure6: "Grating",
    strMeasure7: "3 tbsp",
    strMeasure8: "200g",
    strMeasure9: "1 finely sliced",
    strMeasure10: "200g peeled raw",
    strMeasure11: "Large handful",
    strMeasure12: "Handful",
    strMeasure13: "Grated zest of 1",
    strMeasure14: "25g grated",
    strMeasure15: "Juice of 1",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52931",
    strMeal: "Sugar Pie",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "Canadian",
    strInstructions:
      "Preheat oven to 350 degrees F (175 degrees C). Grease a 9-inch pie dish.\r\nPlace the brown sugar and butter in a mixing bowl, and beat them together with an electric mixer until creamy and very well combined, without lumps. Beat in eggs, one at a time, incorporating the first egg before adding the next one. Add the vanilla extract and salt; beat the flour in, a little at a time, and then the milk, making a creamy batter. Pour the batter into the prepared pie dish.\r\nBake in the preheated oven for 35 minutes; remove pie, and cover the rim with aluminum foil to prevent burning. Return to oven, and bake until the middle sets and the top forms a crusty layer, about 15 more minutes. Let the pie cool to room temperature, then refrigerate for at least 1 hour before serving.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg",
    strTags: "Pie,Desert",
    strYoutube: "https://www.youtube.com/watch?v=uVQ66jiL-Dc",
    strIngredient1: "Brown Sugar",
    strIngredient2: "Butter",
    strIngredient3: "Eggs",
    strIngredient4: "Vanilla Extract",
    strIngredient5: "Salt",
    strIngredient6: "Plain Flour",
    strIngredient7: "Milk",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 cups ",
    strMeasure2: "¼ cup",
    strMeasure3: "2",
    strMeasure4: "1 tsp ",
    strMeasure5: "1 tsp ",
    strMeasure6: "½ cup ",
    strMeasure7: "1 1/2 cups ",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "http://allrecipes.com/recipe/213595/miraculous-canadian-sugar-pie/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52933",
    strMeal: "Rappie Pie",
    strMealAlternate: null,
    strCategory: "Chicken",
    strArea: "Canadian",
    strInstructions:
      "Preheat oven to 400 degrees F (200 degrees C). Grease a 10x14x2-inch baking pan.\r\nHeat margarine in a skillet over medium heat; stir in onion. Cook and stir until onion has softened and turned translucent, about 5 minutes. Reduce heat to low and continue to cook and stir until onion is very tender and dark brown, about 40 minutes more.\r\nBring chicken broth to a boil in a large pot; stir in chicken breasts, reduce heat, and simmer until chicken is no longer pink at the center, about 20 minutes. Remove from heat. Remove chicken breasts to a plate using a slotted spoon; reserve broth.\r\nJuice potatoes with an electric juicer; place dry potato flesh into a bowl and discard juice. Stir salt and pepper into potatoes; stir in enough reserved broth to make the mixture the consistency of oatmeal. Set remaining broth aside.\r\nSpread half of potato mixture evenly into the prepared pan. Lay cooked chicken breast evenly over potatoes; scatter caramelized onion evenly over chicken. Spread remaining potato mixture over onions and chicken to cover.\r\nBake in the preheated oven until golden brown, about 1 hour. Reheat chicken broth; pour over individual servings as desired.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg",
    strTags: "Pie",
    strYoutube: "https://www.youtube.com/watch?v=Ys2kZnTVXAM",
    strIngredient1: "Butter",
    strIngredient2: "Onions",
    strIngredient3: "Chicken Stock",
    strIngredient4: "Chicken Breast",
    strIngredient5: "Potatoes",
    strIngredient6: "Salt",
    strIngredient7: "Black Pepper",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tbs",
    strMeasure2: "2 chopped",
    strMeasure3: "4 qt ",
    strMeasure4: "1.5kg",
    strMeasure5: "4kg",
    strMeasure6: "2 tbs",
    strMeasure7: "1tbsp",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "http://allrecipes.com/recipe/234025/rappie-pie/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52991",
    strMeal: "Mince Pies",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "To make the pastry, rub 225g cold, diced butter into 350g plain flour, then mix in 100g golden caster sugar and a pinch of salt.\r\n\r\nCombine the pastry into a ball – don’t add liquid – and knead it briefly. The dough will be fairly firm, like shortbread dough. You can use the dough immediately, or chill for later.\r\n\r\nPreheat the oven to 200C/gas 6/fan 180C. Line 18 holes of two 12-hole patty tins, by pressing small walnut-sized balls of pastry into each hole.\r\n\r\nSpoon 280g mincemeat into the pies.\r\n\r\nTake slightly smaller balls of pastry than before and pat them out between your hands to make round lids, big enough to cover the pies. \r\n\r\nTop the pies with their lids, pressing the edges gently together to seal – you don’t need to seal them with milk or egg as they will stick on their own. (The pies may now be frozen for up to 1 month).\r\n\r\nBeat 1 small egg and brush the tops of the pies. Bake for 20 mins until golden. Leave to cool in the tin for 5 mins, then remove to a wire rack.\r\n\r\nTo serve, lightly dust with icing sugar.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qe8pf51576795532.jpg",
    strTags: "Christmas",
    strYoutube: "https://www.youtube.com/watch?v=PnXft7lQNJE",
    strIngredient1: "Butter",
    strIngredient2: "Plain Flour",
    strIngredient3: "Caster Sugar",
    strIngredient4: "Mincemeat",
    strIngredient5: "Egg",
    strIngredient6: "Icing Sugar",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "225g",
    strMeasure2: "350g",
    strMeasure3: "100g ",
    strMeasure4: "280g",
    strMeasure5: "1 small",
    strMeasure6: "Topping",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource:
      "https://www.bbcgoodfood.com/recipes/2174/unbelievably-easy-mince-pies",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52857",
    strMeal: "Pumpkin Pie",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "American",
    strInstructions:
      "Place the pumpkin in a large saucepan, cover with water and bring to the boil. Cover with a lid and simmer for 15 mins or until tender. Drain pumpkin; let cool.\r\nHeat oven to 180C/160C fan/gas 4. Roll out the pastry on a lightly floured surface and use it to line a 22cm loose-bottomed tart tin. Chill for 15 mins. Line the pastry with baking parchment and baking beans, then bake for 15 mins. Remove the beans and paper, and cook for a further 10 mins until the base is pale golden and biscuity. Remove from the oven and allow to cool slightly.\r\nIncrease oven to 220C/200C fan/gas 7. Push the cooled pumpkin through a sieve into a large bowl. In a separate bowl, combine the sugar, salt, nutmeg and half the cinnamon. Mix in the beaten eggs, melted butter and milk, then add to the pumpkin purée and stir to combine. Pour into the tart shell and cook for 10 mins, then reduce the temperature to 180C/160C fan/gas 4. Continue to bake for 35-40 mins until the filling has just set.\r\nLeave to cool, then remove the pie from the tin. Mix the remaining cinnamon with the icing sugar and dust over the pie. Serve chilled.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/usuqtp1511385394.jpg",
    strTags: "Halloween,Pie,Desert",
    strYoutube: "https://www.youtube.com/watch?v=hpapqEeb36k",
    strIngredient1: "Pumpkin",
    strIngredient2: "Shortcrust Pastry",
    strIngredient3: "Plain Flour",
    strIngredient4: "Caster Sugar",
    strIngredient5: "Salt",
    strIngredient6: "Nutmeg",
    strIngredient7: "Cinnamon",
    strIngredient8: "Eggs",
    strIngredient9: "Butter",
    strIngredient10: "Milk",
    strIngredient11: "Icing Sugar",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "750g",
    strMeasure2: "350g",
    strMeasure3: "Dusting",
    strMeasure4: "140g",
    strMeasure5: "½ tsp",
    strMeasure6: "½ tsp",
    strMeasure7: "1 tsp ",
    strMeasure8: "2 Beaten ",
    strMeasure9: "25g",
    strMeasure10: "175g",
    strMeasure11: "1 tblsp ",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/1742633/pumpkin-pie",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52859",
    strMeal: "Key Lime Pie",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "American",
    strInstructions:
      "Heat the oven to 160C/fan 140C/gas 3. Whizz the biscuits to crumbs in a food processor (or put in a strong plastic bag and bash with a rolling pin). Mix with the melted butter and press into the base and up the sides of a 22cm loose-based tart tin. Bake in the oven for 10 minutes. Remove and cool.\r\nPut the egg yolks in a large bowl and whisk for a minute with electric beaters. Add the condensed milk and whisk for 3 minutes then add the zest and juice and whisk again for 3 minutes. Pour the filling into the cooled base then put back in the oven for 15 minutes. Cool then chill for at least 3 hours or overnight if you like.\r\nWhen you are ready to serve, carefully remove the pie from the tin and put on a serving plate. To decorate, softly whip together the cream and icing sugar. Dollop or pipe the cream onto the top of the pie and finish with extra lime zest.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qpqtuu1511386216.jpg",
    strTags: "Cake,Pie,Desert,Fruity,Sour",
    strYoutube: "https://www.youtube.com/watch?v=q4Rz7tUkX9A",
    strIngredient1: "Digestive Biscuits",
    strIngredient2: "Butter",
    strIngredient3: "Condensed Milk",
    strIngredient4: "Egg Yolks",
    strIngredient5: "Lime",
    strIngredient6: "Double Cream",
    strIngredient7: "Icing Sugar",
    strIngredient8: "Lime",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "300g",
    strMeasure2: "150g",
    strMeasure3: "400g",
    strMeasure4: "3",
    strMeasure5: "4",
    strMeasure6: "300ml ",
    strMeasure7: "1 tbls",
    strMeasure8: "to serve",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/2155644/key-lime-pie",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52882",
    strMeal: "Three Fish Pie",
    strMealAlternate: null,
    strCategory: "Seafood",
    strArea: "British",
    strInstructions:
      "Preheat the oven to 200C/400F/Gas 6 (180C fan).\r\nPut the potatoes into a saucepan of cold salted water. Bring up to the boil and simmer until completely tender. Drain well and then mash with the butter and milk. Add pepper and taste to check the seasoning. Add salt and more pepper if necessary.\r\nFor the fish filling, melt the butter in a saucepan, add the leeks and stir over the heat. Cover with a lid and simmer gently for 10 minutes, or until soft. Measure the flour into a small bowl. Add the wine and whisk together until smooth.\r\nAdd the milk to the leeks, bring to the boil and then add the wine mixture. Stir briskly until thickened. Season and add the parsley and fish. Stir over the heat for two minutes, then spoon into an ovenproof casserole. Scatter over the eggs. Allow to cool until firm.\r\nSpoon the mashed potatoes over the fish mixture and mark with a fork. Sprinkle with cheese.\r\nBake for 30-40 minutes, or until lightly golden-brown on top and bubbling around the edges.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg",
    strTags: "Fish,Seafood,Dairy,Pie",
    strYoutube: "https://www.youtube.com/watch?v=Ds1Jb8H5Sg8",
    strIngredient1: "Potatoes",
    strIngredient2: "Butter",
    strIngredient3: "Milk",
    strIngredient4: "Gruyere",
    strIngredient5: "Butter",
    strIngredient6: "Leek",
    strIngredient7: "Plain Flour",
    strIngredient8: "White Wine",
    strIngredient9: "Milk",
    strIngredient10: "Parsley",
    strIngredient11: "Salmon",
    strIngredient12: "Haddock",
    strIngredient13: "Smoked Haddock",
    strIngredient14: "Eggs",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1kg",
    strMeasure2: "Knob",
    strMeasure3: "Dash",
    strMeasure4: "50g",
    strMeasure5: "75g",
    strMeasure6: "2 sliced",
    strMeasure7: "75g",
    strMeasure8: "150ml",
    strMeasure9: "568ml",
    strMeasure10: "2 tbs chopped",
    strMeasure11: "250g",
    strMeasure12: "250g",
    strMeasure13: "250g",
    strMeasure14: "6",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/three_fish_pie_58875",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52876",
    strMeal: "Minced Beef Pie",
    strMealAlternate: null,
    strCategory: "Beef",
    strArea: "British",
    strInstructions:
      "Preheat the oven to 200C/400F/Gas 6.\r\nHeat the oil in a deep frying pan and fry the beef mince for 4-5 minutes, breaking it up with a wooden spoon as it browns.\r\nAdd the onion and cook for 2-3 minutes, then stir in the tomato purée and cook for 2-3 more minutes. Stir in the flour and cook for a further minute, then add the chopped mushrooms, the stout or beef stock and a couple of dashes of Worcestershire sauce. Bring to the boil, then reduce the heat, cover the pan with a lid and leave to simmer for 20 minutes. Set aside and leave to cool, then turn the meat mixture into a one litre pie dish.\r\nRoll out the pastry on a floured work surface until it is slightly larger than the pie dish. Gently drape the pastry over the dish, pressing firmly onto the edges. Trim, then shape the edges into a fluted shape.\r\nCut some leaf shapes out of the pastry trimmings and decorate the top of the pie, sticking them to the pastry with the beaten egg yolk.\r\nMake three or four slits in the pastry to allow the steam to escape, then brush the pie with the rest of the beaten egg yolk and bake in the oven for 20-25 minutes, or until golden-brown.\r\nTo serve, slice into wedges.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg",
    strTags: "Pie,Meat",
    strYoutube: "https://www.youtube.com/watch?v=QY47h-uqq5g",
    strIngredient1: "Vegetable Oil",
    strIngredient2: "Minced Beef",
    strIngredient3: "Onion",
    strIngredient4: "Tomato Puree",
    strIngredient5: "Plain Flour",
    strIngredient6: "Mushrooms",
    strIngredient7: "Beef Stock",
    strIngredient8: "Worcestershire Sauce",
    strIngredient9: "Shortcrust Pastry",
    strIngredient10: "Egg Yolks",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tbs",
    strMeasure2: "500g",
    strMeasure3: "1 chopped",
    strMeasure4: "1 tbls",
    strMeasure5: "1 ½ tbsp",
    strMeasure6: "75g",
    strMeasure7: "250ml",
    strMeasure8: "Dash",
    strMeasure9: "400g",
    strMeasure10: "1",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/mincedbeefpie_89198",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52856",
    strMeal: "Choc Chip Pecan Pie",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "American",
    strInstructions:
      "First, make the pastry. Tip the ingredients into a food processor with 1 /4 tsp salt. Blend until the mixture resembles breadcrumbs. Drizzle 2-3 tsp cold water into the funnel while the blade is running – the mixture should start to clump together. Tip onto a work surface and bring together, kneading briefly into a ball. Pat into a disc, wrap in cling film, and chill for at least 20 mins. Heat oven to 200C/180C fan/gas 6.\r\n\r\nRemove the pastry from the fridge and leave at room temperature for 5 mins to soften. Flour the work surface, then unwrap the pastry and roll to a circle the thickness of a £1 coin. Use the pastry to line a deep, 23cm round fluted tin – mine was about 3cm deep. Press the pastry into the corners and up the sides, making sure there are no gaps. Leave 1cm pastry overhanging (save some of the pastry scraps for later). Line with baking parchment (scrunch it up first to make it more pliable) and fill with baking beans. Blind-bake for 15-20 mins until the sides are set, then remove the parchment and beans and return to the oven for 5 mins until golden brown. Trim the pastry so it’s flush with the top of the tin – a small serrated knife is best for this. If there are any cracks, patch them up with the pastry scraps.\r\n\r\nMeanwhile, weigh the butter, syrup and sugars into a pan, and add 1 /4 tsp salt. Heat until the butter has melted and the sugar dissolved, stirring until smooth. Remove from the heat and cool for 10 mins. Reduce oven to 160C/140C fan/gas 3.\r\n\r\nBeat the eggs in a bowl. Add the syrup mixture, vanilla and pecans, and mix until well combined. Pour half the mixture into the tart case, scatter over half the chocolate chips, then cover with the remaining filling and chocolate chips. Bake on the middle shelf for 50-55 mins until set. Remove from the oven and leave to cool, then chill for at least 2 hrs before serving.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/rqvwxt1511384809.jpg",
    strTags: "Pie,Desert,Sweet,Nutty",
    strYoutube: "https://www.youtube.com/watch?v=fDpoT0jvg4Y",
    strIngredient1: "Plain Flour",
    strIngredient2: "Butter",
    strIngredient3: "Cream Cheese",
    strIngredient4: "Icing Sugar",
    strIngredient5: "Butter",
    strIngredient6: "Maple Syrup",
    strIngredient7: "Light Brown Soft Sugar",
    strIngredient8: "Dark Brown Soft Sugar",
    strIngredient9: "Eggs",
    strIngredient10: "Vanilla Extract",
    strIngredient11: "Pecan Nuts",
    strIngredient12: "Dark Chocolate Chips",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "300g",
    strMeasure2: "75g",
    strMeasure3: "100g ",
    strMeasure4: "1 tbls",
    strMeasure5: "150g",
    strMeasure6: "200ml",
    strMeasure7: "250g",
    strMeasure8: "100g ",
    strMeasure9: "4",
    strMeasure10: "1 tsp ",
    strMeasure11: "400g",
    strMeasure12: "200g",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/choc-chip-pecan-pie",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52877",
    strMeal: "Lamb and Potato pie",
    strMealAlternate: null,
    strCategory: "Lamb",
    strArea: "British",
    strInstructions:
      "Dust the meat with flour to lightly coat.\r\nHeat enough vegetable oil in a large saucepan to fill the base, and fry the onion and meat until lightly browned. Season with salt and pepper.\r\nAdd the carrots, stock and more seasoning to taste.\r\nBring to the boil, cover and reduce the heat to a simmer. Simmer for at least an hour or until the meat is tender. Take your time cooking the meat, the longer you leave it to cook, the better the flavour will be.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nAdd the drained potato cubes to the lamb.\r\nTurn the mixture into a pie dish or casserole and cover with the shortcrust pastry. Make three slits in the top of the pastry to release any steam while cooking.\r\nBrush with beaten egg and bake for about 40 minutes, until the pastry is golden brown.\r\nServe.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/sxrpws1511555907.jpg",
    strTags: "Pie",
    strYoutube: "https://www.youtube.com/watch?v=NCyPaaUNYUk",
    strIngredient1: "Lamb Shoulder",
    strIngredient2: "Flour",
    strIngredient3: "Vegetable Oil",
    strIngredient4: "Onion",
    strIngredient5: "Carrots",
    strIngredient6: "Vegetable Stock",
    strIngredient7: "Potatoes",
    strIngredient8: "Shortcrust Pastry",
    strIngredient9: "Eggs",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "500g",
    strMeasure2: "1 tbls",
    strMeasure3: "Dash",
    strMeasure4: "1 sliced",
    strMeasure5: "2 sliced",
    strMeasure6: "350ml/12fl",
    strMeasure7: "500g",
    strMeasure8: "450g",
    strMeasure9: "To Glaze",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/lambandpotatopie_83913",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52878",
    strMeal: "Beef and Oyster pie",
    strMealAlternate: null,
    strCategory: "Beef",
    strArea: "British",
    strInstructions:
      "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
    strTags: "Pie",
    strYoutube: "https://www.youtube.com/watch?v=ONX74yP6JnI",
    strIngredient1: "Beef",
    strIngredient2: "Olive Oil",
    strIngredient3: "Shallots",
    strIngredient4: "Garlic",
    strIngredient5: "Bacon",
    strIngredient6: "Thyme",
    strIngredient7: "Bay Leaf",
    strIngredient8: "Stout",
    strIngredient9: "Beef Stock",
    strIngredient10: "Corn Flour",
    strIngredient11: "Oysters",
    strIngredient12: "Plain Flour",
    strIngredient13: "Salt",
    strIngredient14: "Butter",
    strIngredient15: "Eggs",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "900g",
    strMeasure2: "3 tbs",
    strMeasure3: "3",
    strMeasure4: "2 cloves minced",
    strMeasure5: "125g",
    strMeasure6: "1 tbs chopped",
    strMeasure7: "2",
    strMeasure8: "330ml",
    strMeasure9: "400ml",
    strMeasure10: "2 tbs",
    strMeasure11: "8",
    strMeasure12: "400g",
    strMeasure13: "pinch",
    strMeasure14: "250g",
    strMeasure15: "To Glaze",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52880",
    strMeal: "McSinghs Scotch pie",
    strMealAlternate: null,
    strCategory: "Lamb",
    strArea: "British",
    strInstructions:
      "Heat a large frying pan and toast the cumin seeds for a few minutes, then set aside. Heat the oil in the same pan and fry the onion, garlic, chilli, pepper and a good pinch of salt for around eight minutes, until there is no moisture left. Remove from the heat, stir in the toasted cumin seeds, ground mace (or nutmeg) and ground coriander. Leave to cool.\r\nIn a large bowl mix together the minced lamb, white pepper, fresh coriander, and the cooled spiced onion mixture until combined. Set aside, covered, in the fridge.\r\nPreheat the oven to 200C/400F/Gas 6 and generously grease a 20cm/8in diameter loose-bottomed or springform round cake tin with lard.\r\nTo make the pastry, sift the flour and salt in a large bowl and make a well in the centre.\r\nPut the milk, lard and 90ml/3fl oz of water in a saucepan and heat gently. When the lard has melted, increase the heat and bring to the boil.\r\nPour the boiling liquid into the flour, and use a wooden spoon to combine until cool enough to handle. Bring together into a ball.\r\nDust a work surface with flour and, working quickly, knead the dough briefly – it will be soft and moist. Set aside a third of the pastry and roll the rest out on a well-floured surface. Line the pie dish with the pastry, pressing it right up the sides until it pokes just over the top of the tin.\r\nAdd the filling into the pastry-lined tin bit by bit. As you reach the top, form a slight peak. Roll out the reserved pastry and top the pie with it. Pinch the edges to seal and trim the excess. Poke a hole in the top of the pie and insert a small tube made from aluminium foil to allow steam to escape.\r\nBrush the top of the pie with a little beaten egg yolk, and bake in the preheated oven for 30 minutes (put a tray on the shelf below to catch any drips). Then reduce the temperature to 160C/325F/Gas 3 and cook for a further 1¼ hours until golden-brown. Leave to cool completely before refrigerating for two hours, or overnight.\r\nRun a knife around the edge of the pie, remove from the tin and serve with chutneys, salads or pickles.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/vssrtx1511557680.jpg",
    strTags: "Pie",
    strYoutube: "https://www.youtube.com/watch?v=1nArqhRyszw",
    strIngredient1: "Cumin",
    strIngredient2: "Rapeseed Oil",
    strIngredient3: "Red Onions",
    strIngredient4: "Garlic Clove",
    strIngredient5: "Green Chilli",
    strIngredient6: "Red Pepper",
    strIngredient7: "Nutmeg",
    strIngredient8: "Coriander",
    strIngredient9: "Lamb Mince",
    strIngredient10: "Pepper",
    strIngredient11: "Coriander",
    strIngredient12: "Plain Flour",
    strIngredient13: "Salt",
    strIngredient14: "Milk",
    strIngredient15: "Lard",
    strIngredient16: "Egg Yolks",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tsp",
    strMeasure2: "1 tbs",
    strMeasure3: "2 finely chopped",
    strMeasure4: "6",
    strMeasure5: "3 finely chopped",
    strMeasure6: "1 finely chopped ",
    strMeasure7: "1 tsp ",
    strMeasure8: "2 tsp",
    strMeasure9: "1kg",
    strMeasure10: "1 tsp ",
    strMeasure11: "3 tbs",
    strMeasure12: "340g",
    strMeasure13: "½ tsp",
    strMeasure14: "90 ml ",
    strMeasure15: "150g",
    strMeasure16: "Beaten",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/mcsinghs_scotch_pie_98356",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52874",
    strMeal: "Beef and Mustard Pie",
    strMealAlternate: null,
    strCategory: "Beef",
    strArea: "British",
    strInstructions:
      "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
    strTags: "Meat,Pie",
    strYoutube: "https://www.youtube.com/watch?v=nMyBC9staMU",
    strIngredient1: "Beef",
    strIngredient2: "Plain Flour",
    strIngredient3: "Rapeseed Oil",
    strIngredient4: "Red Wine",
    strIngredient5: "Beef Stock",
    strIngredient6: "Onion",
    strIngredient7: "Carrots",
    strIngredient8: "Thyme",
    strIngredient9: "Mustard",
    strIngredient10: "Egg Yolks",
    strIngredient11: "Puff Pastry",
    strIngredient12: "Green Beans",
    strIngredient13: "Butter",
    strIngredient14: "Salt",
    strIngredient15: "Pepper",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1kg",
    strMeasure2: "2 tbs",
    strMeasure3: "2 tbs",
    strMeasure4: "200ml",
    strMeasure5: "400ml",
    strMeasure6: "1 finely sliced",
    strMeasure7: "2 chopped",
    strMeasure8: "3 sprigs",
    strMeasure9: "2 tbs",
    strMeasure10: "2 free-range",
    strMeasure11: "400g",
    strMeasure12: "300g",
    strMeasure13: "25g",
    strMeasure14: "pinch",
    strMeasure15: "pinch",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52881",
    strMeal: "Steak and Kidney Pie",
    strMealAlternate: null,
    strCategory: "Beef",
    strArea: "British",
    strInstructions:
      "Preheat the oven to 220C/425F/Gas 7\r\nHeat the vegetable oil in a large frying pan, and brown the beef all over. (You may need to do this in batches.) Set aside, then brown the kidneys on both sides in the same pan. Add the onions and cook for 3-4 minutes.\r\nReturn the beef to the pan, sprinkle flour over and coat the meat and onions\r\nAdd the stock to the pan, stir well and bring to the boil.\r\nTurn the heat down and simmer for 1½ hours without a lid. If the liquid evaporates too much, add more stock.\r\nRemove from the heat. Add salt, pepper and Worcestershire sauce and allow to cool completely. Place the cooked meat mixture into a pie dish.\r\nRoll out the pastry to 5mm/¼in thick and 5cm/2in larger than the dish you are using.\r\nUsing a rolling pin, lift the pastry and place it over the top of the pie dish. Trim and crimp the edges with your fingers and thumb.\r\nBrush the surface with the beaten egg mixture and bake for 30-40 minutes until golden-brown and puffed.\r\nServe with creamy mash and steamed vegetables to soak up the gravy.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg",
    strTags: "Pie",
    strYoutube: "https://www.youtube.com/watch?v=oTw5tPt4KmA",
    strIngredient1: "Puff Pastry",
    strIngredient2: "Egg White",
    strIngredient3: "Egg Yolks",
    strIngredient4: "Vegetable Oil",
    strIngredient5: "Beef",
    strIngredient6: "Lamb Kidney",
    strIngredient7: "Onions",
    strIngredient8: "Plain Flour",
    strIngredient9: "Beef Stock",
    strIngredient10: "Salt",
    strIngredient11: "Pepper",
    strIngredient12: "Worcestershire Sauce",
    strIngredient13: null,
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "300g",
    strMeasure2: "Beaten",
    strMeasure3: "Beaten",
    strMeasure4: "2 tbs",
    strMeasure5: "70 ml ",
    strMeasure6: "200g",
    strMeasure7: "2 chopped",
    strMeasure8: "30g",
    strMeasure9: "85 ml ",
    strMeasure10: "pinch",
    strMeasure11: "pinch",
    strMeasure12: "Dash",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbc.co.uk/food/recipes/steakandkidneypie_73308",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53005",
    strMeal: "Strawberry Rhubarb Pie",
    strMealAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Pie Crust:  In a food processor, place the flour, salt, and sugar and process until combined. Add the butter and process until the mixture resembles coarse\r\n\r\nmeal (about 15 seconds). Pour 1/4 cup (60 ml) water in a slow, steady stream, through the feed tube until the dough just holds together when pinched. If necessary, add more water. Do not process more than 30 seconds.\r\nTurn the dough onto your work surface and gather into a ball. Divide the dough in half, flattening each half into a disk, cover with plastic wrap, and refrigerate for about one hour before using. This will chill the butter and relax the gluten in the flour. \r\n\r\nAfter the dough has chilled sufficiently, remove one portion of the dough from the fridge and place it on a lightly floured surface.  Roll the pastry into a 12 inch (30 cm) circle. (To prevent the pastry from sticking to the counter and to ensure uniform thickness, keep lifting up and turning the pastry a quarter turn as you roll (always roll from the center of the pastry outwards).)  Fold the dough in half and gently transfer to a 9 inch (23 cm) pie pan. Brush off any excess flour and trim any overhanging pastry to an edge of 1/2 inch (1.5 cm). Refrigerate the pastry, covered with plastic wrap, while you make the filling. \r\n\r\nRemove the second round of pastry and roll it into a 13 inch (30 cm) circle. Using a pastry wheel or pizza cutter, cut the pastry into about 3/4 inch (2 cm) strips. Place the strips of pastry on a parchment paper-lined baking sheet, cover with plastic wrap, and place in the refrigerator for about 10 minutes. \r\n\r\nMake the Strawberry Rhubarb Filling: Place the cut strawberries and rhubarb in a large bowl. In a small bowl mix together the cornstarch, sugar, and ground cinnamon. \r\n\r\nRemove the chilled pie crust from the fridge. Sprinkle about 2 tablespoons of the sugar mixture over the bottom of the pastry crust. Add the remaining sugar mixture to the strawberries and rhubarb and gently toss to combine. Pour the fruit mixture into the prepared pie shell. Sprinkle the fruit with about 1 teaspoon of lemon juice and dot with 2 tablespoons of butter.\r\n\r\nRemove the lattice pastry from the refrigerator and, starting at the center with the longest strips and working outwards, place half the strips, spacing about 1 inch (2.5 cm) apart, on top of the filling. (Use the shortest pastry strips at the outer edges.) Then, gently fold back, about halfway, every other strip of pastry. Take another strip of pastry and place it perpendicular on top of the first strips of pastry. Unfold the bottom strips of pastry and then fold back the strips that weren't folded back the first time. Lay another strip of pastry perpendicular on top of the filling and then continue with the remaining strips. Trim the edges of the pastry strips, leaving a 1 inch (2.5 cm) overhang. Seal the edges of the pastry strips by folding them under the bottom pastry crust and flute the edges of the pastry. Brush the lattice pastry with milk and sprinkle with a little sugar. Cover and place in the refrigerator while you preheat the oven to 400 degrees F (205 degrees C) and place the oven rack in the lower third of the oven. Put a baking sheet, lined with aluminum foil, on the oven rack (to catch any spills.)\r\n\r\nPlace the pie plate on the hot baking sheet and bake the pie for about 35 minutes and then, if the edges of the pie are browning too much, cover with a foil ring. Continue to bake the pie for about another 10 minutes or until the crust is a golden brown color and the fruit juices begin to bubble.\r\n\r\nRemove the pie from the oven and place on a wire rack to cool for several hours. Serve at room temperature with softly whipped cream or vanilla ice cream. Leftovers can be stored in the refrigerator for about 3 days. Reheat before serving. This pie can be frozen.\r\n\r\nMakes one 9 inch (23 cm) pie.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/178z5o1585514569.jpg",
    strTags: "Pudding,Pie,Baking,Fruity,Glazed",
    strYoutube: "https://www.youtube.com/watch?v=tGw5Pwm4YA0",
    strIngredient1: "Flour",
    strIngredient2: "Salt",
    strIngredient3: "Sugar",
    strIngredient4: "Butter",
    strIngredient5: "Water",
    strIngredient6: "Rhubarb",
    strIngredient7: "Strawberries",
    strIngredient8: "Cornstarch",
    strIngredient9: "Sugar",
    strIngredient10: "Cinnamon",
    strIngredient11: "Lemon Juice",
    strIngredient12: "Unsalted Butter",
    strIngredient13: "Milk",
    strIngredient14: "Sugar",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "350g",
    strMeasure2: "1 tsp ",
    strMeasure3: "2 tbs",
    strMeasure4: "1 cup ",
    strMeasure5: "1/2 cup ",
    strMeasure6: "450g",
    strMeasure7: "450g",
    strMeasure8: "3 tbs",
    strMeasure9: "150g",
    strMeasure10: "1/4 tsp",
    strMeasure11: "1 tsp ",
    strMeasure12: "2 tbs",
    strMeasure13: "2 tbs",
    strMeasure14: "Spinkling",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.joyofbaking.com/StrawberryRhubarbPie.html",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53000",
    strMeal: "Vegetable Shepherds Pie",
    strMealAlternate: null,
    strCategory: "Beef",
    strArea: "Irish",
    strInstructions:
      "Add Ingredients:\r\n\r\n12 cups chopped mixed vegetables\r\n1   cup chopped fresh mushrooms \r\n1   cup pearl onions\r\n\r\nTOPPING:\r\n\r\nPreheat oven to 450°. Bake potatoes on a foil-lined baking sheet until tender, about 45 minutes. Let cool slightly, then peel. Press potatoes through a ricer, food mill, or colander into a large bowl. Add butter; stir until well blended. Stir in milk. Season to taste with salt.\r\n\r\nFILLING:\r\n\r\nSoak dried porcini in 3 cups hot water; set aside. Combine lentils, 1 garlic clove, 1 tsp. salt, and 4 cups water in a medium saucepan. Bring to a boil; reduce heat and simmer, stirring occasionally, until lentils are tender but not mushy, 15–20 minutes. Drain lentils and discard garlic.\r\n\r\nHeat 3 Tbsp. oil in a large heavy pot over medium heat. Add onions and cook, stirring occasionally, until soft, about 12 minutes. Add chopped garlic and cook for 1 minute. Stir in tomato paste. Cook, stirring constantly, until tomato paste is caramelized, 2–3 minutes.\r\n\r\nAdd bay leaves and wine; stir, scraping up any browned bits. Stir in porcini, slowly pouring porcini soaking liquid into pan but leaving any sediment behind. Bring to a simmer and cook until liquid is reduced by half, about 10 minutes. Stir in broth and cook, stirring occasionally, until reduced by half, about 45 minutes.\r\n\r\nStrain mixture into a large saucepan and bring to a boil; discard solids in strainer. Stir cornstarch and 2 Tbsp. water in a small bowl to dissolve. Add cornstarch mixture; simmer until thickened, about 5 minutes. Whisk in miso. Season sauce with salt and pepper. Set aside.\r\n\r\nPreheat oven to 450°. Toss vegetables and pearl onions with remaining 2 Tbsp. oil, 5 garlic cloves, and rosemary sprigs in a large bowl; season with salt and pepper. Divide between 2 rimmed baking sheets. Roast, stirring once, until tender, 20–25 minutes. Transfer garlic cloves to a small bowl; mash well with a fork and stir into sauce. Discard rosemary. DO AHEAD: Lentils, sauce, and vegetables can be made 1 day ahead. Cover separately; chill.\r\nArrange lentils in an even layer in a 3-qt. baking dish; set dish on a foil-lined rimmed baking sheet. Toss roasted vegetables with fresh mushrooms and chopped herbs; layer on top of lentils. Pour sauce over vegetables. Spoon potato mixture evenly over.\r\n\r\nBake until browned and bubbly, about 30 minutes. Let stand for 15 minutes before serving.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/w8umt11583268117.jpg",
    strTags: "Baking",
    strYoutube: "",
    strIngredient1: "Potatoes",
    strIngredient2: "Small Potatoes",
    strIngredient3: "Salted Butter",
    strIngredient4: "Mushrooms",
    strIngredient5: "Brown Lentils",
    strIngredient6: "Garlic",
    strIngredient7: "Kosher Salt",
    strIngredient8: "Onion",
    strIngredient9: "Tomato Puree",
    strIngredient10: "Bay Leaves",
    strIngredient11: "Olive Oil",
    strIngredient12: "Dry White Wine",
    strIngredient13: "Vegetable Stock",
    strIngredient14: "Cornstarch",
    strIngredient15: "Soy Sauce",
    strIngredient16: "Rosemary",
    strIngredient17: "Parsley",
    strIngredient18: "Sage",
    strIngredient19: "Chives",
    strIngredient20: "",
    strMeasure1: "3 Lbs",
    strMeasure2: "3 Lbs",
    strMeasure3: "1/2 cup ",
    strMeasure4: "1 oz ",
    strMeasure5: "3/4 cup ",
    strMeasure6: "6 cloves",
    strMeasure7: "1 tsp ",
    strMeasure8: "3 cups ",
    strMeasure9: "2 tbsp",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: "2 cups ",
    strMeasure13: "8 cups ",
    strMeasure14: "2 tbsp",
    strMeasure15: "2 tsp",
    strMeasure16: "2 sprigs",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52875",
    strMeal: "Chicken Ham and Leek Pie",
    strMealAlternate: null,
    strCategory: "Chicken",
    strArea: "British",
    strInstructions:
      "Heat the chicken stock in a lidded saucepan. Add the chicken breast and bring to a low simmer. Cover with a lid and cook for 10 minutes. Remove the chicken breasts from the water with tongs and place on a plate. Pour the cooking liquor into a large jug.\r\nMelt 25g/1oz of the butter in a large heavy-based saucepan over a low heat. Stir in the leeks and fry gently for two minutes, stirring occasionally until just softened. Add the garlic and cook for a further minute. Add the remaining butter and stir in the flour as soon as the butter has melted. Cook for 30 seconds, stirring constantly.\r\nSlowly pour the milk into the pan, just a little at a time, stirring well between each adding. Gradually add 250ml/10fl oz of the reserved stock and the wine, if using, stirring until the sauce is smooth and thickened slightly. Bring to a gentle simmer and cook for 3 minutes.\r\nSeason the mixture, to taste, with salt and freshly ground black pepper. Remove from the heat and stir in the cream. Pour into a large bowl and cover the surface of the sauce with cling ilm to prevent a skin forming. Set aside to cool.\r\nPreheat the oven to 200C/400F/Gas 6. Put a baking tray in the oven to heat.\r\nFor the pastry, put the flour and butter in a food processor and blend on the pulse setting until the mixture resembles fine breadcrumbs. With the motor running, add the beaten egg and water and blend until the mixture forms a ball. Portion off 250g/10oz of pastry for the lid.\r\nRoll the remaining pastry out on a lightly floured surface, turning the pastry frequently until around 5mm/¼in thick and 4cm/1½in larger than the pie dish. Lift the pastry over the rolling pin and place it gently into the pie dish. Press the pastry firmly up the sides, making sure there are no air bubbles. Leave the excess pastry overhanging the sides.\r\nCut the chicken breasts into 3cm/1¼in pieces. Stir the chicken, ham and leeks into the cooled sauce. Pour the chicken filling into the pie dish. Brush the rim of the dish with beaten egg. Roll out the reserved pastry for the lid.\r\nCover the pie with the pastry lid and press the edges together firmly to seal. Trim any excess pastry.\r\nMake a small hole in the centre of the pie with the tip of a knife. Glaze the top of the pie with beaten egg. Bake on the preheated tray in the centre of the oven for 35-40 minutes or until the pie is golden-brown all over and the filling is piping hot.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg",
    strTags: "Pie,Meat",
    strYoutube: "https://www.youtube.com/watch?v=xr-CpPE_lNk",
    strIngredient1: "Chicken Stock",
    strIngredient2: "Chicken Breast",
    strIngredient3: "Butter",
    strIngredient4: "Leek",
    strIngredient5: "Garlic",
    strIngredient6: "Plain Flour",
    strIngredient7: "Milk",
    strIngredient8: "White Wine",
    strIngredient9: "Double Cream",
    strIngredient10: "Ham",
    strIngredient11: "Sea Salt",
    strIngredient12: "Pepper",
    strIngredient13: "Plain Flour",
    strIngredient14: "Butter",
    strIngredient15: "Free-range Egg, Beaten",
    strIngredient16: "Cold Water",
    strIngredient17: "Free-range Egg, Beaten",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "450ml",
    strMeasure2: "3",
    strMeasure3: "75g",
    strMeasure4: "2 sliced",
    strMeasure5: "2 cloves minced",
    strMeasure6: "50g",
    strMeasure7: "200ml",
    strMeasure8: "3 tbs",
    strMeasure9: "150ml",
    strMeasure10: "150g",
    strMeasure11: "spinkling",
    strMeasure12: "pinch",
    strMeasure13: "350g",
    strMeasure14: "200g",
    strMeasure15: "1",
    strMeasure16: "1 tbls",
    strMeasure17: "1",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "https://www.bbc.co.uk/food/recipes/creamy_chicken_ham_and_03877",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53019",
    strMeal: "Pierogi (Polish Dumplings)",
    strMealAlternate: null,
    strCategory: "Side",
    strArea: "Polish",
    strInstructions:
      "To prepare the sauerkraut filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Add the drained sauerkraut and cook for an additional 5 minutes. Season to taste with salt and pepper, then remove to a plate to cool.\r\n\r\nFor the mashed potato filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Stir into the mashed potatoes, and season with salt and white pepper.\r\n\r\nTo make the dough, beat together the eggs and sour cream until smooth. Sift together the flour, salt, and baking powder; stir into the sour cream mixture until dough comes together. Knead the dough on a lightly floured surface until firm and smooth. Divide the dough in half, then roll out one half to 1/8 inch thickness. Cut into 3 inch rounds using a biscuit cutter.\r\n\r\nPlace a small spoonful of the mashed potato filling into the center of each round. Moisten the edges with water, fold over, and press together with a fork to seal. Repeat procedure with the remaining dough and the sauerkraut filling.\r\n\r\nBring a large pot of lightly salted water to a boil. Add perogies and cook for 3 to 5 minutes or until pierogi float to the top. Remove with a slotted spoon.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/45xxr21593348847.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=lyqDmUroZrI",
    strIngredient1: "Butter",
    strIngredient2: "Chopped Onion",
    strIngredient3: "Sauerkraut",
    strIngredient4: "Butter",
    strIngredient5: "Chopped Onion",
    strIngredient6: "Potatoes",
    strIngredient7: "Eggs",
    strIngredient8: "Sour Cream",
    strIngredient9: "Flour",
    strIngredient10: "Salt",
    strIngredient11: "Baking Powder",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tbs",
    strMeasure2: "1/3 cup",
    strMeasure3: "1 1/2 cups ",
    strMeasure4: "3 tbs",
    strMeasure5: "1/2 cup ",
    strMeasure6: "2 cups ",
    strMeasure7: "3",
    strMeasure8: "1 pot",
    strMeasure9: "3 cups ",
    strMeasure10: "1/4 tsp",
    strMeasure11: "1 tbs",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource:
      "https://www.allrecipes.com/recipe/109914/pierogi-polish-dumplings/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];
